[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Michael Blättler <michael.blaettler@innetag.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
